export const ABBREVIATIONS_TO_STATES = new Map([
	['AL', 'Alabama'],
	['AK', 'Alaska'],
	['AS', 'American Samoa'],
	['AZ', 'Arizona'],
	['AR', 'Arkansas'],
	['AA', 'Armed Forces Americas'],
	['AE', 'Armed Forces Europe'],
	['AP', 'Armed Forces Pacific'],
	['CA', 'California'],
	['CO', 'Colorado'],
	['CT', 'Connecticut'],
	['DE', 'Delaware'],
	['DC', 'District Of Columbia'],
	['FL', 'Florida'],
	['GA', 'Georgia'],
	['GU', 'Guam'],
	['HI', 'Hawaii'],
	['ID', 'Idaho'],
	['IL', 'Illinois'],
	['IN', 'Indiana'],
	['IA', 'Iowa'],
	['KS', 'Kansas'],
	['KY', 'Kentucky'],
	['LA', 'Louisiana'],
	['ME', 'Maine'],
	['MH', 'Marshall Islands'],
	['MD', 'Maryland'],
	['MA', 'Massachusetts'],
	['MI', 'Michigan'],
	['MN', 'Minnesota'],
	['MS', 'Mississippi'],
	['MO', 'Missouri'],
	['MT', 'Montana'],
	['NE', 'Nebraska'],
	['NV', 'Nevada'],
	['NH', 'New Hampshire'],
	['NJ', 'New Jersey'],
	['NM', 'New Mexico'],
	['NY', 'New York'],
	['NC', 'North Carolina'],
	['ND', 'North Dakota'],
	['NP', 'Northern Mariana Islands'],
	['OH', 'Ohio'],
	['OK', 'Oklahoma'],
	['OR', 'Oregon'],
	['PA', 'Pennsylvania'],
	['PR', 'Puerto Rico'],
	['RI', 'Rhode Island'],
	['SC', 'South Carolina'],
	['SD', 'South Dakota'],
	['TN', 'Tennessee'],
	['TX', 'Texas'],
	['VI', 'US Virgin Islands'],
	['UT', 'Utah'],
	['VT', 'Vermont'],
	['VA', 'Virginia'],
	['WA', 'Washington'],
	['WV', 'West Virginia'],
	['WI', 'Wisconsin'],
	['WY', 'Wyoming'],
]);

/** Because the data has magical-numeric IDs (no, they did not just make the simple decision to use state FIPS codes) */
export const STATE_ISO_TO_FEATURE_ID = new Map([
	['AL', 19],
	['AK', 20],
	['AZ', 36],
	['AR', 53],
	['CA', 17],
	['CO', 22],
	['CT', 56],
	['DE', 26],
	['DC', 27],
	['FL', 28],
	['GA', 29],
	['HI', 30],
	['ID', 31],
	['IL', 32],
	['IN', 54],
	['IA', 33],
	['KS', 35],
	['KY', 48],
	['LA', 6],
	['MD', 18],
	['MA', 2],
	['ME', 1],
	['MI', 3],
	['MN', 55],
	['MS', 39],
	['MO', 21],
	['MT', 4],
	['ND', 52],
	['NE', 41],
	['NH', 42],
	['NV', 5],
	['NJ', 40],
	['NM', 43],
	['NY', 7],
	['NC', 8],
	['OH', 9],
	['OK', 45],
	['OR', 46],
	['PA', 10],
	['PR', 14],
	['RI', 11],
	['SC', 34],
	['SD', 15],
	['TN', 24],
	['TX', 13],
	['UT', 23],
	['VA', 50],
	['VT', 49],
	['WA', 12],
	['WI', 16],
	['WV', 51],
	['WY', 25],
]);

export const STATE_ISO_TO_FIPS = new Map([
	['AL', '01'],
	['AK', '02'],
	['AZ', '04'],
	['AR', '05'],
	['CA', '06'],
	['CO', '08'],
	['CT', '09'],
	['DE', '10'],
	['FL', '12'],
	['GA', '13'],
	['HI', '15'],
	['ID', '16'],
	['IL', '17'],
	['IN', '18'],
	['IA', '19'],
	['KS', '20'],
	['KY', '21'],
	['LA', '22'],
	['ME', '23'],
	['MD', '24'],
	['MA', '25'],
	['MI', '26'],
	['MN', '27'],
	['MS', '28'],
	['MO', '29'],
	['MT', '30'],
	['NE', '31'],
	['NV', '32'],
	['NH', '33'],
	['NJ', '34'],
	['NM', '35'],
	['NY', '36'],
	['NC', '37'],
	['ND', '38'],
	['OH', '39'],
	['OK', '40'],
	['OR', '41'],
	['PA', '42'],
	['RI', '44'],
	['SC', '45'],
	['SD', '46'],
	['TN', '47'],
	['TX', '48'],
	['UT', '49'],
	['VT', '50'],
	['VA', '51'],
	['WA', '53'],
	['WV', '54'],
	['WI', '55'],
	['WY', '56'],
	['DC', '11'],
]);
