/**
 * Maps Census STATEFP code to state abbreviation used by PDAP API
 *
 * See {@link https://www2.census.gov/geo/docs/reference/codes2020/national_state2020.txt this file} for more details
 */
export const STATEFP_TO_ABBR = new Map([
	['01', 'AL'],
	['02', 'AK'],
	['04', 'AZ'],
	['05', 'AR'],
	['06', 'CA'],
	['08', 'CO'],
	['09', 'CT'],
	['10', 'DE'],
	['11', 'DC'],
	['12', 'FL'],
	['13', 'GA'],
	['15', 'HI'],
	['16', 'ID'],
	['17', 'IL'],
	['18', 'IN'],
	['19', 'IA'],
	['20', 'KS'],
	['21', 'KY'],
	['22', 'LA'],
	['23', 'ME'],
	['24', 'MD'],
	['25', 'MA'],
	['26', 'MI'],
	['27', 'MN'],
	['28', 'MS'],
	['29', 'MO'],
	['30', 'MT'],
	['31', 'NE'],
	['32', 'NV'],
	['33', 'NH'],
	['34', 'NJ'],
	['35', 'NM'],
	['36', 'NY'],
	['37', 'NC'],
	['38', 'ND'],
	['39', 'OH'],
	['40', 'OK'],
	['41', 'OR'],
	['42', 'PA'],
	['44', 'RI'],
	['45', 'SC'],
	['46', 'SD'],
	['47', 'TN'],
	['48', 'TX'],
	['49', 'UT'],
	['50', 'VT'],
	['51', 'VA'],
	['53', 'WA'],
	['54', 'WV'],
	['55', 'WI'],
	['56', 'WY'],
	['60', 'AS'],
	['66', 'GU'],
	['69', 'MP'],
	['72', 'PR'],
	['74', 'UM'],
	['78', 'VI'],
]);

export const ABBREVIATIONS_TO_STATES = new Map([
	['AL', 'Alabama'],
	['AK', 'Alaska'],
	['AS', 'American Samoa'],
	['AZ', 'Arizona'],
	['AR', 'Arkansas'],
	['AA', 'Armed Forces Americas'],
	['AE', 'Armed Forces Europe'],
	['AP', 'Armed Forces Pacific'],
	['CA', 'California'],
	['CO', 'Colorado'],
	['CT', 'Connecticut'],
	['DE', 'Delaware'],
	['DC', 'District Of Columbia'],
	['FL', 'Florida'],
	['GA', 'Georgia'],
	['GU', 'Guam'],
	['HI', 'Hawaii'],
	['ID', 'Idaho'],
	['IL', 'Illinois'],
	['IN', 'Indiana'],
	['IA', 'Iowa'],
	['KS', 'Kansas'],
	['KY', 'Kentucky'],
	['LA', 'Louisiana'],
	['ME', 'Maine'],
	['MH', 'Marshall Islands'],
	['MD', 'Maryland'],
	['MA', 'Massachusetts'],
	['MI', 'Michigan'],
	['MN', 'Minnesota'],
	['MS', 'Mississippi'],
	['MO', 'Missouri'],
	['MT', 'Montana'],
	['NE', 'Nebraska'],
	['NV', 'Nevada'],
	['NH', 'New Hampshire'],
	['NJ', 'New Jersey'],
	['NM', 'New Mexico'],
	['NY', 'New York'],
	['NC', 'North Carolina'],
	['ND', 'North Dakota'],
	['NP', 'Northern Mariana Islands'],
	['OH', 'Ohio'],
	['OK', 'Oklahoma'],
	['OR', 'Oregon'],
	['PA', 'Pennsylvania'],
	['PR', 'Puerto Rico'],
	['RI', 'Rhode Island'],
	['SC', 'South Carolina'],
	['SD', 'South Dakota'],
	['TN', 'Tennessee'],
	['TX', 'Texas'],
	['VI', 'US Virgin Islands'],
	['UT', 'Utah'],
	['VT', 'Vermont'],
	['VA', 'Virginia'],
	['WA', 'Washington'],
	['WV', 'West Virginia'],
	['WI', 'Wisconsin'],
	['WY', 'Wyoming'],
]);
