export default new Set([
	'Complaints & Misconduct',
	'Daily Activity Logs',
	'Training & Hiring Info',
	'Personnel Records',
	'Annual & Monthly Reports',
	'Budgets & Finances',
	'Contact Info & Agency Meta',
	'Geographic',
	'List of Data Sources',
	'Policies & Contracts',
	'Crime Maps & Reports',
	'Crime Statistics',
	'Records Request Info',
	'Resources',
	'Sex Offender Registry',
	'Wanted Persons',
	'Booking Reports',
	'Court Cases',
	'Incarceration Records',
	'Accident Reports',
	'Arrest Records',
	'Calls for Service',
	'Car GPS',
	'Citations',
	'Dispatch Logs',
	'Dispatch Recordings',
	'Field Contacts',
	'Incident Reports',
	'Misc Police Activity',
	'Officer Involved Shootings',
	'Stops',
	'Surveys',
	'Use of Force Reports',
	'Vehicle Pursuits',
	'Booking Reports',
	'Court Cases',
	'Incarceration Records',
]);
